# Generated by Django 5.0.6 on 2024-07-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fact_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Feminine")],
                max_length=1,
                null=True,
            ),
        ),
    ]
