# Generated by Django 5.0.6 on 2024-07-03 16:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fact_app", "0003_alter_customer_save_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="save_by",
        ),
    ]
